[package]
name = "nau-scripts"
version = "0.1.0"
edition = "2021"

[build-dependencies]
aiken = "1.0.19-alpha"
aiken-lang = "1.0.19-alpha"
aiken-project = "1.0.19-alpha"

[dependencies]
hex = "0.4.3"
naumachia = {path = "..", version = "0.2.0"}
serde_json = "1.0"
