name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --workspace
    - name: Run tests
      run: cargo test --verbose --workspace
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.NIGHTLY_RUST_VERSION }}
          components: rustfmt
      - name: Rustfmt check
        run: cargo +${{ env.NIGHTLY_RUST_VERSION }} fmt --all -- --check


  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Audit
      run: cargo audit
